config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clients, only: %i[index show] do
    resources :body_stats, only: %i[create]
    resources :workout_plans, only: %i[create]
  end

  resources :workout_plan, only: [] do
    resources :workout_sessions, only: %i[create]
  end

  resources :workout_sessions, only: %i[show] do
    post :copy, to: "workout_sessions#copy", as: :copy
    resources :session_exercises, only: %i[create]
    resources :comments, only: %i[create]
    resources :questions, only: %i[index create]
  end

  resources :exercises, only: %i[index]

  resources :session_exercises, only: %i[destroy]

  resources :contracts, only: %i[create]
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :workout_plan
  has_many :session_exercises, dependent: :destroy
  has_many :exercises, through: :session_exercises
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :session_name, presence: true
  validates :date_time, presence: true
  validates :with_trainer, inclusion: { in: [true, false] }
  validates :duration, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 30,
    message: "must be at least 30 minutes"
  }
  # validate :date_time_cannot_be_in_the_past
  validate :date_time_cannot_be_outside_of_plan_date
  validate :date_time_unique

  scope :upcoming, -> { where("date_time >= ?", Time.current) }

  def date_time_cannot_be_in_the_past
    if date_time.present? && date_time < Time.current
      errors.add(:date_time, "can't be in the past")
    end
  end

  def date_time_cannot_be_outside_of_plan_date
    session_date = date_time.to_date
    plan_range = workout_plan.starting_date..workout_plan.ending_date

    if date_time.present? && !plan_range.cover?(session_date)
      errors.add(:date_time, "must be within plan period")
    end
  end

  def date_time_unique
    trainer = workout_plan.trainer
    client = workout_plan.client
    trainer_sessions = trainer.workout_sessions_as_trainer.map(&:date_time)
    client_sessions = client.workout_sessions_as_client.map(&:date_time)
    if trainer_sessions.include?(date_time)
      errors.add(:date_time, "Trainer already has a session on that date. Please choose another date and time")
    end
    if client_sessions.include?(date_time)
      errors.add(:date_time, "Client already has a session on this date. Please choose another date and time")
    end
  end
end

app/controllers/workout_sessions_controller.rb
class WorkoutSessionsController < ApplicationController
  before_action :set_workout_session, only: %i[show copy]
  before_action :set_client, only: %i[create]

  def show
    authorize @workout_session
    @session_exercises = @workout_session.session_exercises.any? ? @workout_session.session_exercises : []
    @session_exercise = SessionExercise.new
    @comment = Comment.new
    @questions = current_user.questions
    @question = Question.new
  end

  # Method to copy existing session
  def copy
    @workout_session_copy = @workout_session.deep_clone include: :session_exercises
    @workout_session_copy.assign_attributes(workout_session_params)
    authorize @workout_session_copy
    if @workout_session_copy.save
      redirect_to workout_session_path(@workout_session_copy), notice: "Workout session copied successfully."
    else
      # render client show page if workout plan is invalid
      @client = set_client
      @workout_plans = @client.workout_plans_as_client
      @body_stat = BodyStat.new
      @workout_plan = WorkoutPlan.new
      render "clients/show", status: :unprocessable_entity
    end
  end

  def create
    @workout_session = WorkoutSession.new(workout_session_params)
    authorize @workout_session
    if @workout_session.save
      redirect_to workout_session_path(@workout_session), notice: "Workout session created successfully."
    else
      # render client show page if workout plan is invalid
      @workout_plans = @client.workout_plans_as_client
      @body_stat = BodyStat.new
      @workout_plan = WorkoutPlan.new
      render "clients/show", status: :unprocessable_entity
    end
  end


  private

  def set_workout_session
    @workout_session = WorkoutSession.find(params[:id] || params[:workout_session_id])
  end

  def set_client
    workout_plan = WorkoutPlan.find(params[:workout_plan_id])
    @client = User.find(workout_plan.client_id)
  end

  def workout_session_params
    params.require(:workout_session).permit(:session_name, :date_time, :duration, :with_trainer, :workout_plan_id)
  end
end

app/views/workout_sessions/_ai_exercise_form.html.erb
<% scroll ||= false %>
<%= turbo_frame_tag :new_exercise_form do %>
  <div class="container py-4" data-controller="ai-form-behavior ai-session">
    <div class="row justify-content-end">
      <div class="col-lg-10 col-md-10 col-sm-12">
        <div class="card border-0 rounded-5 shadow-sm">
          <div class="card-header bg-danger border-0 rounded-top-5 py-4">
            <h3 class="text-center text-light mt-0 mb-2 fw-bold">Add exercises</h3>
            <p class="text-center text-light mb-0">Customize your client's exercise</p>
          </div>
          <div class="card-body pt-3 pb-4">
            <%= simple_form_for([workout_session, session_exercise], data: { controller: "session-exercise-form", action: "submit->ai-form-behavior#submit" }) do |f| %>
              <div class="row g-4 justify-content-center align-items-center">
                <!-- Exercise Selection -->
                <!-- For using Tom Select -->
                <!-- 1. importmap pin tom-select -> go to importmap.rb, change the version source if needed -->
                <!-- 2. generate stimulus controller and mount the controller on the select input field-->
                <!-- 3. add a line to import tom select into the stimulus controller -->
                <!-- 4. In application.html.erb, add a link for tom select stylesheet-->
                <% exercise_photos = Exercise.all.map { |exercise| [exercise.id, photo_url(exercise)] }.to_h %>
                <!-- Exercise Preview -->
                <div class="col-12 mb-3 text-center">
                  <%= cl_image_tag "", id: "photo-preview", alt: "Exercise preview", class: "border border-danger border-4 rounded-4", style: "max-width: 200px; display: none;" %>
                </div>
                <div class="col-12 m-0" data-exercise-photos="<%= exercise_photos.to_json %>">
                  <%= f.input :exercise_id,
                    collection: Exercise.all.map { |exercise| [ "#{exercise.name}", exercise.id ] },
                    label: "Choose exercise",
                    input_html: {
                      id: "select-exercise",
                      data: { ai_session_target: "tomSelect"},
                      class: "form-select form-select-lg"
                    } %>
                </div>
                <!-- Load -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :load, "Load:", class: "form-label mb-0" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :load,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">kg</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Repetitions -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :repetitions, "Reps:", class: "form-label" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :repetitions,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">reps</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Sets -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :set, "Sets:", class: "form-label" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :set,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">sets</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Submit Button -->
                <div class="row justify-content-between align-items-center">
                  <div class="col-6 text-center mt-3 ps-1">
                    <%= f.button :submit, "Add Exercise", class: "btn btn-danger rounded-5" %>
                  </div>
                  <div class="col-6 text-center mt-3 d-flex justify-content-end pe-1">
                    <%= button_tag "Cancel", class: "btn btn-info rounded-5", data: { action: "click->ai-form-behavior#cancel" } %>
                    <!-- Button in form by default is to submit, if the button is used for any other purpose, add preventDefault() in JS -->
                    <!-- f.button is linked to the form object of simple form, button_tag is rails helper -->
                    <!-- Adding data-controller in f.button or any simple_form component has to be done inside input_html: {} -->
                    <!-- Adding data-controller in button_tag doesn't require input_html: {} -->
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/workout_sessions/_copy_form.html.erb
<div class="container py-0">
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-10 col-sm-12">
      <div class="card border-0 rounded-5 shadow-sm">
        <div class="card-header rounded-top-5 bg-danger border-0 py-4">
          <h3 class="text-center text-light fw-bold my-0">Copy a Workout Session</h3>
        </div>
        <div class="card-body pt-3 pb-4 mb-2">
          <!-- add namespace to make form id unique -->
          <%= simple_form_for [workout_session, empty_workout_session], method: :post, url: workout_session_copy_path(workout_session), namespace: dom_id(workout_session) do |f| %>
            <%= f.input :session_name, label: "Focus of the session", input_html: { value: "Copy of #{workout_session.session_name}", class: "rounded-3" } %>
            <%= f.input :date_time, as: :string, label: "Choose date and time", input_html: { data: {controller: "datepicker-workout-session"}, class: "rounded-3" } %>
            <div class="col-12 my-0">
              <%= f.label :duration, "Session duration", class: "form-label" %>
              <div class="input-group mb-3">
                <%= f.input :duration, label: false, input_html: { class: "form-control rounded-start-3", placeholder: "30" }, wrapper: false %>
                <span class="input-group-text rounded-end-3">minutes</span>
              </div>
            </div>
            <%# <%= f.input :duration, label: "Session duration (minutes)?",input_html: { class: "form-control", placeholder: "30" }%>
            <div class="col-12 my-0">
              <%= f.input :with_trainer,
                  as: :radio_buttons,
                  label: "Session type",
                  collection: [[ 'With trainer', true ], [ 'Solo', false ]],
                  input_html: { class: "session-selector" },
                  item_wrapper_class: 'session-item' %>
            </div>
            <%# <%= f.input :with_trainer, as: :radio_buttons, collection: [[ 'Yes', true ], [ 'No', false ]], label: "With a trainer?" %>
            <div class="col-12 text-center pt-1">
              <%= f.submit "Add a session", class: "btn btn-danger px-5 rounded-5" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workout_sessions/_exercise_details_display.erb
<div class="exercise-details py-0 px-3">
  <!--<h3 class="mt-0 text-center"><%= exercise.exercise.name %></h3>-->
  <% unless exercise.exercise.main_muscles.blank?%>
    <p><strong>Muscle Group:</strong> <%= exercise.exercise.main_muscles %></p>
  <% end %>
  <% unless exercise.exercise.equipment.blank?%>
    <p><strong>Equipment:</strong> <%= exercise.exercise.equipment %></p>
  <% end %>
  <% unless exercise.exercise.starting_position.blank?%>
    <p><strong>Starting Position:</strong> <%= exercise.exercise.starting_position %></p>
  <% end %>
  <% unless exercise.exercise.execution.blank?%>
    <p><strong>Execution:</strong> <%= exercise.exercise.execution %></p>
  <% end %>
</div>

app/views/workout_sessions/_exercise_display.html.erb
<% scroll ||= false %>
<div id="<%= dom_id(session_exercise) %>" class="mb-3" data-controller="scroll-into-view" data-scroll-into-view-scroll-value="<%=  scroll %>">
  <div class="card mb-3 shadow-sm border-0 rounded-3 overflow-hidden" data-controller="display-toggle form-toggle-display">
    <div class="row g-0 align-items-center">
      <!-- Image -->
      <div class="col-12 col-md-4 text-center p-0" style="background-color: #f8f9fa;">
        <%= cl_image_tag(session_exercise.exercise.photo.key,
                  class: "img-fluid",
                  style: "max-height: 180px; object-fit: contain; background-color: #f8f9fa;") %>
      </div>
      <!-- Text -->
      <div class="col-12 col-md-8 p-3">
        <h3 class="mt-0"><%= session_exercise.exercise.name %></h3>
        <p class="text-center">
          <% unless session_exercise.load.zero? %>
            <span class="badge rounded-pill px-3 py-2 me-2 border bg-white text-dark fw-normal" style="font-size: 16px;">
              <%= session_exercise.load %> kg
            </span>
          <% end %>
          <span class="badge rounded-pill px-3 py-2 me-2 border bg-white text-dark fw-normal" style="font-size: 16px;">
            <%= session_exercise.repetitions %> reps
          </span>
          <span class="badge rounded-pill px-3 py-2 border bg-white text-dark fw-normal" style="font-size: 16px;">
            <%= session_exercise.set %> sets
          </span>
        </p>
        <div class="row align-items-center">
          <div class="col-9 d-flex align-items-center justify-content-center">
            <button type="button" class="btn custom-btn my-2 rounded-pill px-3 py-2 me-2 fw-bold fs-6" data-action="click->display-toggle#fire">
              <i class="fa-solid fa-eye"></i> Exercise details
            </button>
          </div>
          <div class="col-3 d-flex align-items-center justify-content-start">
            <%= button_to session_exercise_path(session_exercise),
                        method: :delete,
                        form: { data: { turbo_confirm: "Are you sure?" } },
                        class: "btn custom-btn rounded-4" do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div data-display-toggle-target="togglableElement" class="session-display d-none">
      <% if session_exercise.present? %>
        <%= render 'workout_sessions/exercise_details_display', exercise: session_exercise %>
      <% end %>
    </div>
  </div>
</div>

app/views/workout_sessions/_new_exercise.html.erb
<%= turbo_frame_tag :new_exercise_form do %>
  <div class="container pt-0 pb-2">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-10 col-sm-12">
        <div class="card border-0 rounded-5 shadow-sm">
          <div class="card-header bg-danger border-0 rounded-top-5 py-4">
            <h3 class="text-center text-light mt-0 mb-2 fw-bold">Add exercises</h3>
            <p class="text-center text-light mb-0">Customize your client's exercise</p>
          </div>
          <div class="card-body pt-3 pb-4">
            <%= simple_form_for([workout_session, session_exercise], data: { controller: "session-exercise-form", action: "turbo:submit-end->session-exercise-form#reset" }) do |f| %>
              <div class="row g-4 justify-content-center align-items-center">
                <!-- Exercise Selection -->
                <!-- For using Tom Select -->
                <!-- 1. importmap pin tom-select -> go to importmap.rb, change the version source if needed -->
                <!-- 2. generate stimulus controller and mount the controller on the select input field-->
                <!-- 3. add a line to import tom select into the stimulus controller -->
                <!-- 4. In application.html.erb, add a link for tom select stylesheet-->
                <% exercise_photos = Exercise.all.map { |exercise| [exercise.id, photo_url(exercise)] }.to_h %>
                <!-- Exercise Preview -->
                <div class="col-12 mb-3 text-center">
                  <%= cl_image_tag "", id: "photo-preview", alt: "Exercise preview", class: "border border-danger border-4 rounded-4", style: "max-width: 200px; display: none;" %>
                </div>
                <div class="col-12 m-0" data-exercise-photos="<%= exercise_photos.to_json %>">
                  <%= f.input :exercise_id,
                    collection: Exercise.all.map { |exercise| [ "#{exercise.name}", exercise.id ] },
                    label: "Choose exercise",
                    input_html: {
                      id: "select-exercise",
                      data: { session_exercise_form_target: "tomSelect"},
                      class: "form-select"
                    } %>
                </div>
                <!-- Load -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :load, "Load:", class: "form-label mb-0" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :load,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3 placeholder-light",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">kg</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Repetitions -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :repetitions, "Reps:", class: "form-label" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :repetitions,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">reps</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Sets -->
                <div class="col-12 mt-1">
                  <div class="row">
                    <div class="col-3" style="padding-left: 12px; padding-top: 5px;">
                      <%= f.label :set, "Sets:", class: "form-label" %>
                    </div>
                    <div class="col-9">
                      <div class="input-group mb-3">
                        <%= f.input :set,
                      label: false,
                      input_html: {
                        class: "form-control rounded-start-3",
                        placeholder: "10"
                      }, wrapper: false %>
                        <span class="input-group-text rounded-end-3">sets</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Submit Button -->
                <div class="col-12 text-center mt-3">
                  <%= f.button :submit, "Add Exercise", class: "btn btn-danger px-5 rounded-5" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/workout_sessions/_workout_session_form.html.erb
<div class="container pt-0 pb-5">
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-10 col-sm-12">
      <div class="card border-0 rounded-5 shadow-sm">
        <div class="card-header bg-danger border-0 rounded-top-5 py-4">
          <h3 class="text-center text-light mt-0 mb-2 fw-bold">Schedule a Workout Session</h3>
          <p class="text-light text-center mb-0">Prep <%= workout_plan.client.first_name %>'s next win!</p>
        </div>
        <div class="card-body p-5">
          <!-- add namespace to make form id unique -->
          <%= simple_form_for [workout_plan, workout_session], method: :post, url: workout_plan_workout_sessions_path(workout_plan), namespace: dom_id(workout_plan) do |f| %>
            <div class="row g-4 justify-content-center align-items-center">
              <div class="col-12 my-0">
                <%= f.input :session_name, label: "Focus of the session", input_html: { class: "rounded-3" } %>
              </div>
              <div class="col-12 my-0">
                <%= f.input :date_time, as: :string, label: "Date and time", label_html: {for: dom_id(workout_plan)}, input_html: { data: {controller: "datepicker-workout-session"}, id: dom_id(workout_plan), class: "rounded-3" } %>
                <!--value type for normal date_time input is datetime-->
              </div>
              <div class="col-12 my-0">
                <%= f.label :duration, "Session duration", class: "form-label" %>
                <div class="input-group mb-3">
                  <%= f.input :duration, label: false, input_html: { class: "form-control rounded-start-3", placeholder: "30" }, wrapper: false %>
                  <span class="input-group-text rounded-end-3">minutes</span>
                </div>
              </div>
              <div class="col-12 my-0">
                <%= f.input :with_trainer,
                  as: :radio_buttons,
                  label: "Session type",
                  collection: [[ 'With trainer', true ], [ 'Solo', false ]],
                  input_html: { class: "session-selector" },
                  item_wrapper_class: 'session-item' %>
                <%# <%= f.input :with_trainer, as: :radio_buttons, collection: [[ 'Yes', true ], [ 'No', false ]], label: "With a trainer?", class: "mb-0"%>
              </div>
              <%= f.hidden_field :workout_plan_id, value: workout_plan.id %>
              <div class="col-12 text-center pt-1">
                <%= f.submit "Add Session", class: "btn btn-danger px-5 rounded-5" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workout_sessions/show.html.erb
<div class="container mt-3 mb-5">
  <div class="col-12">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <%= link_to "← Back", client_path(@workout_session.workout_plan.client), class: "link-button btn btn-outline-secondary rounded-pill" %>
      <h3 class="my-2 badge rounded-pill px-3 py-2 me-2 bg-info text-dark fw-normal fs-6"><i class="fa-solid fa-clock"></i> <%= @workout_session.date_time.strftime("%a %b %e at %l:%M %p") %></h3>
    </div>
    <div class="row">
      <div class="col-12 col-md-12 col-lg-9 margin-bottom-responsive">
        <h2 class="my-0"><%= @workout_session.workout_plan.client.first_name %>'s <%= @workout_session.session_name.split(" ")[0] %> training</h2>
      </div>
      <div class="col-12 col-md-12 col-lg-3 flex-responsive mt-2 mb-4">
        <button type="button"
        class="link-button badge rounded-pill px-3 py-2 bg-danger text-light fw-normal fs-6"
        data-bs-toggle="modal"
        data-bs-target="#formModal">
          Add Session Exercise
        </button>
      </div>
    </div>
  </div>
  <div class="row justify-content-between g-1">
    <!-- Exercises Box -->
    <div class="border-round-responsive-start card p-3 border-0 col-12 col-md-7 bg-white" id="session_exercises">
      <% if @session_exercises.blank? %>
        <h3><i class="fa-solid fa-star"></i> Workout magic starts here! </h3>
      <% else %>
        <div>
          <% @session_exercises.each do |session_exercise| %>
            <%= render "workout_sessions/exercise_display", session_exercise: session_exercise %>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- Comments section -->
    <div class="col-12 col-md-5 margin-top-responsive">
      <div class="container chat mt-0 border-round-responsive-end">
        <h3 class="mt-2"><i class="fa-solid fa-file-pen pe-2" style="color: #b15965;"></i>Leave a note</h3>
        <div id="comment-section" class="comments">
          <% @workout_session.comments.each do |comment| %>
            <%= render "comments/comment", comment: comment %>
          <% end %>
        </div>
        <div class="comment-form">
          <%= render "comments/comment_form", workout_session: @workout_session, comment: @comment, user: current_user %>
        </div>
      </div>
    </div>
  </div>
  <!-- AI section -->
  <div class="container chatbot rounded-5 ai-margin-top">
    <h3 class="mt-2"><i class="fa-solid fa-comments pe-2" style="color: #b15965;"></i>Chat with Fitty</h3>
    <div id="questions">
      <% @workout_session.questions.each do |question| %>
        <%= render "questions/question", question: question %>
      <% end %>
    </div>
    <div class="question-form">
      <%= render "questions/question_form", workout_session: @workout_session, question: @question%>
    </div>
  </div>
</div>
<!-- Add Exercise Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="addExerciseModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <%# <h5 class="modal-title" id="addExerciseModalLabel">Add Session Exercise</h5> %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pt-2 pb-5">
        <%= render 'workout_sessions/new_exercise', workout_session: @workout_session, session_exercise: @session_exercise %>
      </div>
    </div>
  </div>
</div>