config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clients, only: %i[index show] do
    resources :body_stats, only: %i[create]
    resources :workout_plans, only: %i[create]
  end

  resources :workout_plan, only: [] do
    resources :workout_sessions, only: %i[create]
  end

  resources :workout_sessions, only: %i[show] do
    post :copy, to: "workout_sessions#copy", as: :copy
    resources :session_exercises, only: %i[create]
    resources :comments, only: %i[create]
    resources :questions, only: %i[index create]
  end

  resources :exercises, only: %i[index]

  resources :session_exercises, only: %i[destroy]

  resources :contracts, only: %i[create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer_navbar.html.erb
<div class="navbar navbar-dark">
  <div class="mobile-nav">
    <% unless user_signed_in? %>
      <div class="nav-icon">
        <%= link_to new_user_session_path, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
          <i class="fa-solid fa-circle-user" style="color: #ffffff; font-size: 24px"></i>
        <% end %>
      </div>
      <div class="nav-icon">
        <%= link_to root_path, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
          <i class="fa-solid fa-house" style="color: #ffffff; font-size: 24px"></i>
        <% end %>
      </div>
    <% else %>
      <div class="nav-icon">
        <%= link_to root_path, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
          <i class="fa-solid fa-house" style="color: #ffffff; font-size: 24px"></i>
        <% end %>
      </div>
      <% if current_user.trainer? %>
        <div class="nav-icon">
          <%= link_to clients_path, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
            <i class="fa-solid fa-users" style="color: #ffffff; font-size: 24px"></i>
          <% end %>
        </div>
      <% else %>
        <div class="nav-icon">
          <%= link_to client_path(current_user), class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
            <i class="fa-solid fa-id-card-clip" style="color: #ffffff; font-size: 24px"></i>
          <% end %>
        </div>
      <% end %>
      <div class="nav-icon">
        <%= link_to exercises_path, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
          <i class="fa-solid fa-book" style="color: #ffffff; font-size: 24px"></i>
        <% end %>
      </div>
      <div class="nav-icon">
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-button", style: "border: none; background-color: $danger; display: inline-block;" do %>
          <i class="fa-solid fa-right-from-bracket" style="color: #ffffff; font-size: 24px"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">
<meta name="msapplication-TileColor" content="#B15965">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#B15965">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("fitez-logo.png", size: "100x30", alt: "FitEZ logo") %>
    <% end %>
    <% unless user_signed_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% else %>
      <button class="navbar-toggler avatar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <% if current_user.photo.key.nil? %>
          <%= image_tag("icons/apple-icon-180x180.png", class: "avatar", alt: "dropdown menu") %>
        <% else %>
          <%= cl_image_tag(current_user.photo.key, class: "avatar", alt: "dropdown menu") %>
        <% end %>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if current_user.trainer? %>
            <li class="nav-item active">
              <%= link_to "Clients", clients_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Exercise Library", exercises_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},  class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>