config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clients, only: %i[index show] do
    resources :body_stats, only: %i[create]
    resources :workout_plans, only: %i[create]
  end

  resources :workout_plan, only: [] do
    resources :workout_sessions, only: %i[create]
  end

  resources :workout_sessions, only: %i[show] do
    post :copy, to: "workout_sessions#copy", as: :copy
    resources :session_exercises, only: %i[create]
    resources :comments, only: %i[create]
    resources :questions, only: %i[index create]
  end

  resources :exercises, only: %i[index]

  resources :session_exercises, only: %i[destroy]

  resources :contracts, only: %i[create]
end

app/models/workout_plan.rb
class WorkoutPlan < ApplicationRecord
  belongs_to :trainer, class_name: 'User'
  belongs_to :client, class_name: 'User'
  has_many :workout_sessions, dependent: :destroy

  validates :starting_date, :ending_date, presence: true
  validates :scheduled_trainer_session, presence: true
  # validate :starting_date_cannot_be_in_the_past
  # validate :ending_date_cannot_be_in_the_past
  validate :plan_date_cannot_be_reverse

  scope :upcoming, -> { where("starting_date >= ?", Date.today) }

  def starting_date_cannot_be_in_the_past
    if starting_date.present? && starting_date < Date.today
      errors.add(:starting_date, "can't be in the past")
    end
  end

  def ending_date_cannot_be_in_the_past
    if ending_date.present? && ending_date < Date.today
      errors.add(:ending_date, "can't be in the past")
    end
  end

  def plan_date_cannot_be_reverse
    if starting_date.present? && ending_date.present? && ending_date < starting_date
      errors.add(:ending_date, "can't be before starting date")
    end
  end

  def trainer_session_count
    workout_sessions.where(with_trainer: true).count
  end
end

app/controllers/workout_plans_controller.rb
class WorkoutPlansController < ApplicationController
  before_action :set_client, only: %i[create]

  def create
    date_range = params[:workout_plan][:starting_date].split(" to ")
    @workout_plan = WorkoutPlan.new(
      starting_date: date_range[0],
      ending_date: date_range[1],
      trainer_id: current_user.id,
      client_id: @client.id,
      scheduled_trainer_session: params[:workout_plan][:scheduled_trainer_session]
    )
    authorize @workout_plan
    if @workout_plan.save
      @workout_session = WorkoutSession.new
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:workout_plans, partial: "clients/workout_plan_display",
                                                                    locals: { workout_plans: @workout_plans, plan: @workout_plan, workout_session: @workout_session, workout_plan: @workout_plan })
        end
        format.html { redirect_to client_path(@client), notice: "Workout plan created successfully." }
      end
    else
      # render client show page if workout plan is invalid
      @workout_plans = @client.workout_plans_as_client
      @body_stat = BodyStat.new
      @workout_session = WorkoutSession.new
      render "clients/show", status: :unprocessable_entity
    end
  end

  private

  def set_client
    @client = User.find(params[:client_id])
  end
end

app/views/workout_plans/_workout_plan_form.html.erb
<%= turbo_frame_tag :new_plan_form do %>
  <div class="container py-4">
    <div class="row justify-content-end">
      <div class="col-lg-10 col-md-10 col-sm-12">
        <div class="card border-0 rounded-5 shadow-sm">
          <div class="card-header bg-danger light-gray border-0 rounded-top-5 py-4">
            <h3 class="text-center text-light mt-0 mb-2 fw-bold">Plan <%= client.first_name %>'s Next Workout Journey</h3>
            <p class="text-center text-light mb-0">Set your client’s path to success!</p>
          </div>
          <div class="card-body p-5">
            <%= simple_form_for [client, workout_plan], data: { controller: "client-side-forms", action: "turbo:submit-end->client-side-forms#reset" }, method: :post, url: client_workout_plans_path(client) do |f| %>
              <div class="row g-4 justify-content-center align-items-center">
                <div class="col-12 my-0">
                  <%= f.input :starting_date,
                    as: :string,
                    label: "Select a date range",
                    input_html: { data: {controller: "datepicker-workout-plan"}, class: "rounded-3" } %>
                </div>
                <div class="col-12 my-0">
                  <%= f.label :scheduled_trainer_session, "Number of trainer sessions", class: "form-label" %>
                  <div class="input-group mb-3">
                    <%= f.input :scheduled_trainer_session, label: false, input_html: { class: "form-control rounded-start-3", placeholder: "6" }, wrapper: false %>
                    <span class="input-group-text rounded-end-3">sessions</span>
                  </div>
                </div>
                <%= f.hidden_field :client_id, value: client.id %>
                <div class="col-12 text-center pt-1">
                  <%= f.submit "Add Plan",  class: "btn btn-danger px-5 rounded-5" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>